name: platon
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pyfastx>=1.1.0
  - pyrodigal>=3.3.0
  - pyhmmer>=0.10.0
  - diamond>=2.0.14
  - blast>=2.12.0
  - infernal>=1.1.4
  - mummer4>=4.0.0rc1
  - snakemake==7.30.1
