name: platon
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.78
  - prodigal>=2.6.3
  - diamond>=2.0.14
  - blast>=2.12.0
  - hmmer>=3.3.1
  - infernal>=1.1.4
  - snakemake>=7.32.3
  - mummer4>=4.0.0rc1
